---
- name: Restart kube-loadbalancer container
  vars:
    service_name: loadbalancer
    service: "{{ loadbalancer_services[service_name] }}"
  become: true
  shell: docker rm {{ service.container_name }} -f
  failed_when: false
  notify:
    - Start kube-loadbalancer container

- name: Start kube-loadbalancer container
  vars:
    service_name: loadbalancer
    service: "{{ loadbalancer_services[service_name] }}"
  become: true
  shell: docker run -d \
           --name {{ service.container_name }} \
           -v {{ loadbalancer_volumes }} \
           --net host \
           --restart=always {{ service.image }}