---
####################
# Common dependence
####################
common_dependent_packages:
  - gcc
  - python-setuptools
  - python-devel
  - python-pip
  - python-devel
  - libffi-devel
  - openssl-devel

change_selinux: True
selinux_state: "disabled"