---
- name: Ensuring haproxy and keepalived directories exist
  file:
    path: "/etc/{{ item }}"
    state: "directory"
  become: true
  loop:
    - haproxy
    - keepalived
  when: inventory_hostname in groups['kube-master']

- name: Copy keepalived confs
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  become: true
  when: inventory_hostname in groups['kube-master']
  notify:
    - Restart keepalived services

- name: Copy haproxy confs
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  become: true
  when: inventory_hostname in groups['kube-master']
  notify:
    - Restart haproxy services

# - name: Check keepalived service
#   service_check:
#     service_name: keepalived
#     service_type: service
#   when:
#     - inventory_hostname in groups['kube-master']
#   notify:
#     - Restart keepalived services

# - name: Check haproxy service
#   service_check:
#     service_name: haproxy
#     service_type: service
#   when:
#     - inventory_hostname in groups['kube-master']
#   notify:
#     - Restart haproxy services
