---
- name: Get kube images list by kubeadm config
  kube_runtime:
    image_repository: "{{ image_repository }}"
    kubernetes_version: "{{ kubernetes_version }}"
    runtime_type: docker
    runtime_action: get
  register: kube_images
  run_once: True
  when: inventory_hostname in groups['kube-master']

- set_fact:
    images_list: "{{ kube_images.result.images_list }}"
  changed_when: false

- name: Pull kube images for kubernetes nodes
  kube_runtime:
    image: "{{ item.image_repo }}:{{ item.image_tag }}"
    runtime_action: pull
    runtime_type: docker
  loop: "{{ images_list }}"
  loop_control:
    label:
      - "{{ item.image_repo }}"
      - "{{ item.image_tag }}"
  when:
    - inventory_hostname in groups[item.group]

- name: Pull metrics server images
  kube_runtime:
    image: "{{ item }}"
    runtime_action: pull
    runtime_type: docker
  loop: "{{ metrics_server_images }}"
  when:
    - inventory_hostname in groups['kubernetes']
    - enable_metrics_server | bool
