---
- name: Ensuring config directories not exist
  file:
    path: "{{ node_config_directory }}/loadbalancer"
    state: "absent"
  become: true
  with_dict: "{{ loadbalancer_services }}"
  when: inventory_hostname in groups['kubernetes']
  notify:
    - Remove kube-loadbalancer container
