---
project_name: "loadbalancer"

loadbalancer_services:
  loadbalancer:
    container_name: kube_loadbalancer
    group: kubernetes
    image: "{{ loadbalancer_image }}"
    volumes: "{{ loadbalancer_volumes }}"
    enabled: true


#################
# Docker options
#################
loadbalancer_volumes: "/etc/kubernetes-ansible/loadbalancer:/etc/kube-nginx:rw"