---
project_name: "loadbalancer"

loadbalancer_services:
  loadbalancer:
    container_name: kube_loadbalancer
    group: kubernetes
    image: "{{ loadbalancer_image }}"
    volumes: "{{ loadbalancer_volumes }}"
    enabled: true


#################
# Docker options
#################
loadbalancer_image: "jacky06/lb-nginx:v1.0"
loadbalancer_volumes: "/etc/kubernetes-ansible/loadbalancer:/etc/lb-nginx:rw"